title: Information Theory
description: Notes on information theory
theme: just-the-docs
math: mathjax
markdown: kramdown

# url: https://just-the-docs.github.io

search_enabled: true # enable searching across website (true by default)
search.heading_level: 2 # Split pages into sections that can be searched individually
search.previews: 3 # Maximum amount of previews per search result, Default: 3
search.preview_words_before: 5 # Maximum amount of words to display before a matched word in the preview, Default: 5
search.preview_words_after: 10 # Maximum amount of words to display after a matched word in the preview, Default: 10

# auxillary links shown at the top right on all pages. 
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# External navigation links all the way at the bottom of the sidebar
# nav_external_links:
#   - title: Just the Docs on GitHub
#     url: https://github.com/just-the-docs/just-the-docs
#     hide_icon: false # set to true to hide the external link icon - defaults to false
#     opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false